# Which image to build from?
FROM dmcushing/httpd_base

# Make directory /usr/local/apache2/your-domain-2

# Copy website to /usr/local/apache2/your-domain-2

# Copy *.pem files to /usr/local/apache2/conf/sites/

# Copy your-domain-2.class.cety.online.conf to /usr/local/apache2/conf/sites/

# Expose needed ports
EXPOSE 80
EXPOSE 443